name: Run Tests

on:
  # Trigger on pushes to main/dev and PRs targeting them
  push:
    branches: [main, develop, 8-setup-cicd-with-github-actions]
  pull_request:
    branches: [main, develop]
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_COMPILE_BYTECODE: "1"
      UV_LINK_MODE: "copy"
      UV_NO_DEV: "1"
      UV_TOOL_BIN_DIR: "/usr/local/bin"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run python -m unittest
